name: Laravel CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  laravel-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, bcmath
        coverage: none

    - name: Install dependencies
      run: |
          echo "Installing dependencies..."
          # Check for new composer dependencies
          if [ -f "composer.lock" ]; then
            echo "Running composer install..."
            composer install --no-dev --optimize-autoloader
          fi
          # Check for new npm dependencies
          if [ -f "package-lock.json" ]; then
            echo "Checking for new npm dependencies..."
            npm ci
          fi

    - name: Run migrations
      run: |
          echo "Running database migrations..."
          php artisan migrate --force

    - name: Build assets
      run: |
          echo "Building assets..."
          npm run build
