name: Laravel CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  laravel-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Change to your PHP version
        extensions: fileinfo, other-extensions-if-needed

    - name: Install Composer Dependencies
      run: |
        echo "Installing Composer dependencies..."
        composer install --no-dev --optimize-autoloader

    - name: Install Node.js Dependencies
      run: |
        echo "Installing Node.js dependencies..."
        npm ci

    - name: Run Migrations
      run: |
        echo "Running migrations..."
        php artisan migrate

    - name: Build Assets
      run: |
        echo "Building assets..."
        npm run build
